### PR TITLE
v2.0.0

### PR DESCRIPTION
**Pull request by handshake-enthusiast**

### CODE REVIEW

**Comment by pinheadmz** [comment]
huh thats weird, I thought I pushed this to master months ago

**Comment by pinheadmz** [comment]
@handshake-enthusiast I'm a little confused here, where did you get this commit from?

**Comment by handshake-enthusiast** [comment]
@pinheadmz https://github.com/pinheadmz/palmreader/releases/tag/v2.0.0

**Comment by pinheadmz** [comment]
So weird. Looks like I pushed the tag without merging the commit or something

**Comment by pinheadmz** [comment]
Thanks!

**Comment by handshake-enthusiast** [comment]
Previously that commit was saying  
>This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

on GitHub:  

This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

Also just FYI I couldn't create a pull request from a tag, see https://github.com/orgs/community/discussions/23870.

**Pull request merged**
